server:
  port: 8099
spring:
  profiles:
    active: dev2

# 设置选择哪个配置文件
#spring:
#  profiles:
#    active: dev

#person:
#  last_name: 1399237176@qq.com
#  #age: ${10} 不支持${}语法
#  age: 10
#  boss: false
#  birth: 2020/01/01
#  maps: { k1: v1,k2: 12 }
#  lists:
#    - abc
#    - def
#    - hdf
#  dog:
#    name: 黑狗
#    age: 12

person01:
  last_name: 张三${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2020/01/01
  maps: { k1: v1,k2: 12 }
  lists:
    - abc
    - def
    - hdf
  dog:
    name: 黑狗
    age: 12

---
server:
  port: 8083
spring:
  profiles: dev2

---
server:
  port: 8084
spring:
  profiles: prod2